# Generated by cucumber-sinatra. (2015-01-09 11:05:06 +0000)

ENV['RACK_ENV'] = 'test'

require File.join(File.dirname(__FILE__), '..', '..', 'lib/ronin_badge.rb')

require 'capybara'
require 'capybara/cucumber'
require 'rspec'

Capybara.app = Ronin-Badge

class Ronin-BadgeWorld
  include Capybara::DSL
  include RSpec::Expectations
  include RSpec::Matchers
end

World do
  Ronin-BadgeWorld.new
end
